name: Build and deploy ASP.Net Core app to Azure Web App - LesterMDevSecOpsDAST

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      contents: read  # necesario para checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore eShopOnWeb.sln

      - name: Build
        run: dotnet build eShopOnWeb.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish eShopOnWeb.sln -c Release -o ${{ github.workspace }}/publish --no-build

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'LesterMDevSecOpsDAST'
          slot-name: 'Production'
          package: ${{ github.workspace }}/publish
